// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTcPYpTeDPjJ9pZzucVvCas1TXF2OUXWQ',
    appId: '1:397104818734:web:d0cedcf3494850d80f4dbf',
    messagingSenderId: '397104818734',
    projectId: 'smarthousedb-mmd',
    authDomain: 'smarthousedb-mmd.firebaseapp.com',
    databaseURL: 'https://smarthousedb-mmd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smarthousedb-mmd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5cO1ecQHaKL3culZMV_lKTLFN58Erql8',
    appId: '1:397104818734:android:11928dd8d26deb020f4dbf',
    messagingSenderId: '397104818734',
    projectId: 'smarthousedb-mmd',
    databaseURL: 'https://smarthousedb-mmd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smarthousedb-mmd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByVtMItpVchyE4QMHmKWc8K_j8WJ5gmsA',
    appId: '1:397104818734:ios:c1f890acc25e04310f4dbf',
    messagingSenderId: '397104818734',
    projectId: 'smarthousedb-mmd',
    databaseURL: 'https://smarthousedb-mmd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smarthousedb-mmd.firebasestorage.app',
    iosBundleId: 'com.example.smartHome',
  );
}
